[versions]
adventure = "4.25.0"
paper = "1.21.3-R0.1-SNAPSHOT"
velocity = "3.4.0-SNAPSHOT"
acf= "0.5.1-SNAPSHOT"
configlib= "4.6.3"
classgraph = "4.8.179"

[libraries]
adventure-api = { group = "net.kyori", name = "adventure-api", version.ref = "adventure" }
adventure-text-minimessage = { group = "net.kyori", name = "adventure-text-minimessage", version.ref = "adventure" }
adventure-text-serializer-legacy = { group = "net.kyori", name = "adventure-text-serializer-legacy", version.ref = "adventure" }

paper = { group = "io.papermc.paper", name = "paper-api", version.ref = "paper" }
velocity = { group = "com.velocitypowered", name = "velocity-api", version.ref = "velocity" }

acf-paper = { group = "co.aikar", name = "acf-paper", version.ref = "acf" }
acf-velocity = { group = "co.aikar", name = "acf-velocity", version.ref = "acf" }

configlib-yaml = { group = "de.exlll", name = "configlib-yaml", version.ref = "configlib" }
classgraph = { group = "io.github.classgraph", name = "classgraph", version.ref = "classgraph" }

[bundles]
adventure = ["adventure-api", "adventure-text-minimessage"]
adventure-serializers = ["adventure-text-serializer-legacy"]